// Configuration file for client 
if (typeof(vidteq) == 'undefined') { vidteq = {}; }
vidteq._vidteqCfg = {};
vidteq._vidteqCfg.cloneImageUrl = "http://10.4.71.210/stage/cgi-bin/outflv.pl?city=bangalore&img=" ;
vidteq._vidteqCfg.ucDownloadUrl = "vs/uploadUc.php?city=bangalore&action=downloadSelfieImage&img=" ;
vidteq._vidteqCfg.tilecacheBaseUrl = "http://10.4.71.210/stage/vs/tilecache.php?" ;
vidteq._vidteqCfg.videoUrlOgg = "http://10.4.71.200/stage/bangalore/ogg_512/" ;
vidteq._vidteqCfg.emailUrl = "cgi-bin/emailPost.pl" ;
vidteq._vidteqCfg.imageLogosLoc = "/Bangalore/hand_crafted/logos/" ;
vidteq._vidteqCfg.cmaDefaultDemoRouteLat = "12.980938" ;
vidteq._vidteqCfg.softTouchUrl = "cgi-bin/softTouch.pl" ;
vidteq._vidteqCfg.cmaDefaultDemoRouteText = "Cubbon Road" ;
vidteq._vidteqCfg.customHtmlUrl = "/Bangalore/hand_crafted/customDataHtml/" ;
vidteq._vidteqCfg.imageLandmarkLogosLoc = "/Bangalore/hand_crafted/logos/landmark/" ;
vidteq._vidteqCfg.debug = "1" ;
vidteq._vidteqCfg.resolutions = "0.000686646,0.000343323,0.000171661,0.000085831,0.000042915,0.000021458,0.00001072883606,0.000005364418,2.68220901489258e-06" ;
vidteq._vidteqCfg.selfieRouteStartGeom = "POINT(77.618047 12.972636)" ;
vidteq._vidteqCfg.imageCategoryLogosLoc = "images/category_logos/" ;
vidteq._vidteqCfg.videoUrlMp4 = "http://10.4.71.200/stage/bangalore/mp4_512/" ;
vidteq._vidteqCfg.lowBwcustomVideoUrl = "/Bangalore/hand_crafted/customVideos/256/" ;
vidteq._vidteqCfg.demoImageCount = "10" ;
vidteq._vidteqCfg.demoListUrl = "ads/bangalore/flv/demoFile.txt" ;
vidteq._vidteqCfg.tilecacheVideoLayer = "BANG_VAGE" ;
vidteq._vidteqCfg.custom360Images = "/Bangalore/hand_crafted/custom360/" ;
vidteq._vidteqCfg.centerLat = "12.96" ;
vidteq._vidteqCfg.videoUrl = "http://10.4.71.200/stage/flv512/" ;
vidteq._vidteqCfg.resExtent = "76.9921875,12.3046875,78.22265625,13.7109375" ;
vidteq._vidteqCfg.tilecachePoi = "vs/tilecachePoi.php" ;
vidteq._vidteqCfg.nemoApi = "api/nemo/v1" ;
vidteq._vidteqCfg.demoRouteStart = "Bengaluru International Airport" ;
vidteq._vidteqCfg.imgTileUrl = "cgi-bin/imgTile.pl" ;
vidteq._vidteqCfg.locationSearchUrl = "http://localhost:none/" ;
vidteq._vidteqCfg.missingVideoDebug = "0" ;
vidteq._vidteqCfg.tilecacheUrl = "http://10.4.71.210/stage/vs/tilecache.php?" ;
vidteq._vidteqCfg.customCategoryLogosLoc = "/Bangalore/hand_crafted/logos/category_logos/" ;
vidteq._vidteqCfg.selfieRouteStart = "M G Road" ;
vidteq._vidteqCfg.cmaDefaultHomeExtent = "77.71882,12.80352,77.74601,12.81451" ;
vidteq._vidteqCfg.demoRouteStartGeom = "POINT(77.710727 13.199889)" ;
vidteq._vidteqCfg.custom3DData = "/Bangalore/hand_crafted/customThreeD/" ;
vidteq._vidteqCfg.widgetKeys = "magicHappensUrl,lightPullUrl,emailUrl,tilecacheUrl,tilecacheBaseUrl,imageLogosLoc,cloneImageUrl,feedbackFormUrl,tilecachePoi,stdLibraryCategoryLoc,nemoApi" ;
vidteq._vidteqCfg.maxExtent = "76.9921875,12.3046875,78.22265625,13.7109375" ;
vidteq._vidteqCfg.city = "bangalore" ;
vidteq._vidteqCfg.leadTouchUrl = "cgi-bin/leadTouch.pl" ;
vidteq._vidteqCfg.cmaDefaultDemoRouteLon = "77.597515" ;
vidteq._vidteqCfg.highBwcustomVideoUrl = "/Bangalore/hand_crafted/customVideos/512/" ;
vidteq._vidteqCfg.demoRouteEndGeom = "POINT(77.590793 12.979534)" ;
vidteq._vidteqCfg.homeComingUrl = "cgi-bin/homeComing.pl" ;
vidteq._vidteqCfg.magicHappensUrl = "cgi-bin/magicHappens.pl" ;
vidteq._vidteqCfg.imageLoc = "http://10.4.71.200/images" ;
vidteq._vidteqCfg.stdLibraryCategoryLoc = "/stdLibrary/logos/category_logos/" ;
vidteq._vidteqCfg.lightPullUrl = "cgi-bin/lightPull.pl" ;
vidteq._vidteqCfg.imageUrl = "http://10.4.71.210/stage/cgi-bin/outflv.pl?city=bangalore&rawimg=" ;
vidteq._vidteqCfg.tilecacheBaseLayer = "BANG_BUTTERFLY" ;
vidteq._vidteqCfg.tilecacheVideoUrl = "http://10.4.71.210/stage/vs/tilecache.php?" ;
vidteq._vidteqCfg.centerLon = "77.6" ;
vidteq._vidteqCfg.topZoom = "10" ;
vidteq._vidteqCfg.demoRouteEnd = "Vidhan Soudha" ;
